<?php

/**
 * Acade Lotear
 */
define("TB_ACL", "SC_ACL");
define("TB_PESSOA", "PESSOA");
define("TB_PESSOA_FISICA", "PESSOA_FISICA");
define("TB_PESSOA_JURIDICA", "PESSOA_JURIDICA");
define("TB_REPRESENTANTE", "REPRESENTANTE");
define("TB_CORRETOR", "CORRETOR");
define("TB_PARCERIA", "PARCERIA");
define("TB_DOWNLOAD", "DOWNLOAD");
define("TB_EMPREENDIMENTO", "EMPREENDIMENTO");
define("TB_LOTES", "LOTES");
define("TB_BANCO", "BANCO");
define("TB_CONTRATO", "CONTRATO");
define("TB_CONTRATO_ITENS","CONTRATO_ITENS");
define("TB_CONTRATO_HISTORICO", "CONTRATO_HISTORICO");
define("TB_DISTRATO", "DISTRATO");
define("TB_PARCELA", "PARCELA");
define("TB_PARCELA_HISTORICO", "PARCELA_HISTORICO");
define("TB_PARCELA_DISTRATO", "PARCELA_DISTRATO");
define("TB_PARCELA_COMISSAO_CORRETOR", "PARCELA_COMISSAO_CORRETOR");
define("TB_PARCELA_COMISSAO_IMOBILIARIA", "PARCELA_COMISSAO_IMOBILIARIA");
define("TB_CORRETOR_EMPREENDIMENTO", "CORRETOR_EMPREENDIMENTO");
define("TB_DOCUMENTO", "DOCUMENTO");
define("TB_ASSINATURA", "ASSINATURA");
define("TB_USUARIO_EMPREENDIMENTO", "USUARIO_EMPREENDIMENTO");
define("TB_CONTATO", "CONTATO");
define("TB_INDICE", "INDICE");
define("TB_AGRUPADA", "SC_TABELA_AGRUPADA");
define("TB_USUARIO", "SC_USUARIO");
define("TB_CIDADE", "SC_CIDADE");
define("TB_HISTORICO_CARTA", "HISTORICO_CARTA");
define("TB_CARTA_PARCELA", "CARTA_PARCELA");
define("TB_HISTORICO_REAJUSTE", "HISTORICO_REAJUSTE");
define("TB_REMESSA", "REMESSA");
define("TB_TRANSFERENCIA", "TRANSFERENCIA");
define("TB_NEGOCIACAO", "NEGOCIACAO");
define("TB_PARCELA_NEGOCIADA", "PARCELA_NEGOCIADA");
define("TB_CONFISSAO", "CONFISSAO");
define("TB_CONFISSAO_LOTE", "CONFISSAO_LOTE");
define("TB_SINAL", "SINAL");
define("TB_DECLARACOES", "DECLARACOES");
define("TB_RESERVA_LOTE", "RESERVA_LOTE");
define("TB_CLIENTE", "CLIENTE");
define("TB_ADITIVO", "ADITIVO");
define("TB_LOG_ACESSO", "LOG_ACESSO");
define("TB_CARTA_COBRANCA", "CARTA_COBRANCA");
define("TB_CONTRATO_PESSOA", "CONTRATO_PESSOA");
define("TB_CONTROLLER", "SC_CONTROLLER");

/**
 * Painel de Vendas
 */
define("TB_INDICACAO", "INDICACAO");
define("TB_INDICACAO_CONTATO", "INDICACAO_CONTATO");
define("TB_LOGO_EMPREENDIMENTO", "LOGO_EMPREENDIMENTO");
define("TB_PARAMETRO_COMISSAO", "PARAMETRO_COMISSAO");
define("TB_TABELA_PRECO", "TABELA_PRECO");
define("TB_TABELA_PRECO_LOTES", "TABELA_PRECO_LOTES");

